baseurl = "http://allincamera.github.io/"
languageCode = "en-us"
title = "All in Camera"
theme = "hyde-x"
disqusShortname = "httpallincameragithubio"

[params]
        
    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if omitted) is true.
    truncate = false

    # Used when a given page doesn't set its own.
    defaultDescription = "Everything about Camera"
    defaultKeywords = "Camera, Imaging, Tech, technique, ISP, algorithm"

    # Hide estimated reading time for posts.
    # Default (if omitted) is false.
    hideReadingTime = false

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-0b"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Optional additional custom CSS file URL, will override other styles.
    customCSS = ""

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "Here we discuss all about camera."

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Blog"

    # Metadata used to drive integrations.
    googleAnalytics = "Your Google Analytics tracking code"
    gravatarHash = "7100bb8dad0bb0641c343caf30e9613d"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/allincamera"
    bitbucket = ""
    stackOverflow = ""
    linkedin = "https://www.linkedin.com/in/xiadan"
    googleplus = "https://plus.google.com/u/0/112601184917141694227"
    facebook = ""
    twitter = "https://twitter.com/ptthisdan"
    youtube = ""

    # Other social-like sidebar links
    rss = true  # switch to true to enable RSS icon link
    #flattr = "3pe60j"  # populate with your flattr uid
    
[author]   
    name = "All in Camera"

[taxonomies]
    # Optional. Use if you want tags and lists.
    category = "categories"